### ISSUE TITLE
Bug: Twitch App is Installing `AceGUI-3.0: SFX-Widgets`

### ISSUE THREAD

**Issue by CruelDrool** [SFX-WoW/Masque#118]
**Game Version**
Retail - 8.3.7

**Add-On Version**
8.3.0

**Describe the Issue**
Fresh install/update of of `Masque` via Twitch App. `AceGUI-3.0: SFX-Widgets` gets installed as a separate addon and thus gets loaded by default. I wasn't aware that it would be installed, so I was greeted with a Lua-error.

**Error Message**

```text
1x ...dOns\AceGUI-3.0_SFX-Widgets\Widgets\SFX-Info-URL.lua:18: Cannot find a library instance of "AceGUI-3.0".
[string "=[C]"]: in function `error'
[string "@AceGUI-3.0_SFX-Widgets\LibStub\LibStub.lua"]:38: in function `LibStub'
[string "@AceGUI-3.0_SFX-Widgets\Widgets\SFX-Info-URL.lua"]:18: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "AceGUI-3.0"."
```

I know that you've set SFX-Widgets as an external, but it is also present in `Libs\` and gets loaded by `Libs\Libs.xml` . I don't load `AceGUI` separately either. What is the intention here?

**Comment by StormFX** [comment]
I think this may be because I manually edited the relations on WoW Ace. I've fixed it, but I'll have to manually push another release for it to stick. I have a few changes I want to make first, though, so it may be a day or two. For now, just delete the separate libraries. (Ace3, LibDBIcon-1.0, AceGUI-3.0_SFX-Widgets)

**Comment by StormFX** [comment]
This should be fixed with the latest release. Closing.
