### ISSUE TITLE
Bug: HotKey Offsets are not Being Applied

### ISSUE THREAD

**Issue by Gethe** [SFX-WoW/Masque#14]
![Imgur](http://i.imgur.com/ZvHkNJ9.png)

When I updated from 7.2.0 to 7.2.3, the hotkey text no longer gets placed where defined in my skin. No matter what values I use for `HotKey.OffsetX` or `HotKey.OffsetY`, it always ends up in the wrong place.

I am using Bartender with [this skin](https://github.com/RealUI/RealUI/blob/develop/Interface/AddOns/!Aurora_RealUI/AddOns/Masque.lua) (this happens even after setting `Masque_Version = 70200`)

**Comment by StormFX** [comment]
I removed the code that overwrote `HotKey.SetPoint` because it could cause taint and because Blizzard stopped using it. But apparently Nevcairel's LibActionButton-1.0 is still using it. I may have to implement an interim fix until he updates it, assuming he even will. It's a bit annoying since it shouldn't be changing it on every single update.

**Comment by StormFX** [comment]
On another note, is RealUI doing something wonky with the Cooldown and Cooldown Count? I've a user on WoW Interface saying that since I switched to a hook on the `SetCooldown` method of the Cooldown frame, his Cooldown Count isn't showing up.

**Comment by Gethe** [comment]
Yeah, RealUI has a [custom cooldown count](https://github.com/RealUI/RealUI/blob/develop/Interface/AddOns/nibRealUI/Modules/CooldownCount.lua#L181) and the new hook is preventing that from showing.

**Comment by StormFX** [comment]
Hm. I was under the impression that hooksecurefunc allowed for multiple hooks. Now I need to find something else to hook. :/

**Comment by Gethe** [comment]
I think it's because I'm hooking the meta method while you're hooking the widget method, and the widget method takes precedence.

**Comment by StormFX** [comment]
The only alternative is to use a countered recursive hook. I'll have to hook the SetSwipeColor to set the swipe color and then in the hook, exit out if I'm inside the hook already. Eg:

```Lua
local function Hook_SetSwipeColor(Region, ...)
    if Region.__InHook then return end
    Region.__InHook = true
    -- Get the custom r, g, b, a values
    Region:SetSwipeColor(r, g, b, a)
    Region.__InHook = nil
end
```

I'm assuming the `SetSwipeColor` just calls a `SetVertexColor` on the swipe texture object, but we can't access the object itself so that eliminates option. We need a `GetSwipeTexture` method. :/

**Comment by StormFX** [comment]
As far as the HotKey goes, I'm looking for something to hook into to counter LAB changing it.

**Comment by StormFX** [comment]
I actually [posted a ticket](https://www.wowace.com/projects/libactionbutton-1-0/issues/22) on LibActionButton-1.0 about this issue. It calls `SetPoint()` depending on a few variables but is only actually visible in _one_ of the positions. Thus, there's no valid reason for it be called in the `UpdateHotkeys` function. Instead, it should be called in the `CreateButton` method.

**Comment by StormFX** [comment]
Should be fixed.
