### ISSUE TITLE
Bug: Error Message

### ISSUE THREAD

**Issue by Nillx** [SFX-WoW/Masque#251]
### Game Flavor

Retail

### Game Version

10.0

### Add-On Version

9.2.7

### Description

Im getting this error but im not  sure if its a Masque issue or Bagnon. Im using the Bagnon_Masque addon that lets me skin Bagnon as well.

### Error Message

```text
2x bad argument #3 to '?' (Usage: self:SetSwipeTexture(texture [, color]))
[string "=[C]"]: in function `SetSwipeTexture'
[string "@Interface/AddOns/Masque/Core/Regions/Frame.lua"]:140: in function <Interface/AddOns/Masque/Core/Regions/Frame.lua:106>
[string "@Interface/AddOns/Masque/Core/Button.lua"]:157: in function <Interface/AddOns/Masque/Core/Button.lua:52>
[string "@Interface/AddOns/Masque/Core/Group.lua"]:211: in function `RemoveButton'
[string "@Interface/AddOns/Bagnon_Masque/Bagnon_Masque.lua"]:56: in function `?'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/itemGroup.lua"]:183: in function `ForAll'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/itemGroup.lua"]:114: in function `func'
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/MutexDelay-1.0-2/MutexDelay-1.0.lua"]:36: in function <...mon/Wildpants/libs/MutexDelay-1.0/MutexDelay-1.0.lua:30>

Locals:
(*temporary) = "bad argument #3 to '?' (Usage: self:SetSwipeTexture(texture [, color]))"
```

### Steps to Reproduce

Randomly happens.

**Comment by StormFX** [comment]
Masque 9.2.7 is not compatible with Dragonflight. You'll need to update to the alpha or the beta that I'm about to release.

**Comment by Nillx** [comment]
Very well, thanks!

**Comment by TreizeEU** [comment]
I don't know if it's related, but it might help people?

For me, I have to scroll in the Addons-list to reveal the red + button next to Masque. Otherwise, loading options does nothing for me until I do that. Even closing the entire window doesn't help me.

Not sure how that would work for someone who doesn't have enough addons to scroll past Masque (up or down) in the list. 

I use latest 10.0.0-beta-3 version of Masque.
