### ISSUE TITLE
Square texture on Unitframes Target Pets etc.

### ISSUE THREAD

**Issue by Maximos7** [SFX-WoW/Masque#297]
### Game Flavor

Retail

### Game Version

latest

### Add-On Version

latest

### Description

It doesnt become rounded on the player unitframe, pet, target etc. Instead a square is there and its really ugly :/ 
https://github.com/jordonwow/bigdebuffs/issues/537
We also posted the problem on Bigdebuffs addon cause it also happens there. Disabling Masque for Bigdebuffs works but, you know, its not looking good like that :P can it be fixed somehow? Thank you very much!

**Comment by StormFX** [comment]
This has nothing to do with Masque. Based on the image in the referenced issue, Masque is working as intended. I suggest _not_ using square skins for icons that you want to be round because, you know, square skins are, well, _square_. :p

You could try setting the color of the opacity of the `Normal` texture to 0 (via the color picker) or just disable that icon group in Masque, as it _seems_ like the "issue" is with the icon "frame" (`Normal` texture) and its absence defeats the purpose of it being skinned in the first place.

**Comment by Maximos7** [comment]
Hm i ll experiment a bit. I am using Darion Masque and i really like it. Can i use 2 different Addons? Example Darion on all other things and a circle one for unitframes?

**Comment by Maximos7** [comment]
Yeah i confirmed, it works using two skins ;)
