### ISSUE TITLE
Bug: Global Setting not Applying to All WeakAuras

### ISSUE THREAD

**Issue by Talimar** [SFX-WoW/Masque#388]
### Game Flavor

Retail

### Game Version

11.0

### Add-On Version

11.0.0

### Description

I have Masque set to apply "zoomed" to all weakauras, however it's not applying to all auras in a pack I just imported.
It appears to be at random which ones are excluded. 

If I duplicate an aura inside the pack, it will automatically get zoomed applied, so I'm assuming something goes awry during import.

### Steps to Reproduce

Import aura: https://wago.io/5zeUdSWFD

### Screenshots

![Wow_7BKqYMJ1Ll](https://github.com/user-attachments/assets/8753a046-9b29-4b9f-a0e9-5e287b13a8f9)
![Wow_gLXXzPWIVg](https://github.com/user-attachments/assets/25ba159c-43b0-4e39-82dd-af6a203bcd11)

**Comment by StormFX** [comment]
1. Disable WeakAuras and `/reload`.
2. Open Masque's options and go to General Settings > Developer, click the "Clean Database" button and then `/reload` again.
3. Enable WeakAuras and /`reload`.
4. Select the skin you want for WeakAuras.

You may need to delete the WA group first and add it back after. In any case, skins are hierarchy-based, so Global > Addon > Group. Because of the way inheritance works, any group that is manually set ONCE will NOT inherit the skin of its parent if the parent is changed while that group is inactive.

To demonstrate:

1. WeakAuras set to Blizzard Modern.
2. Cleanse_Spirit is added.
3. Cleanse_Spirit is disabled.
4. WeakAuras is set to Zoomed.
5. Cleanse_Spirit is enabled.

**Comment by StormFX** [comment]
Also, for what it's worth, I was able to important that WA and ever button was skinned properly with **Caith**.

**Comment by Talimar** [comment]
Yep that worked thanks.

**Comment by StormFX** [comment]
You bet!
